-- Tabla mínima para captar leads desde la website LINK
create table if not exists public.website_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  business text not null,
  email text not null,
  need text not null,
  source text default 'website-link',
  service text default 'consulta-general',
  created_at timestamptz default now()
);

alter table public.website_leads enable row level security;
-- No se crea policy pública de INSERT: el endpoint server-side usa SERVICE_ROLE.
